"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _home from './home.bones.json'
import _login from './login.bones.json'
import _assign_lawyer from './assign-lawyer.bones.json'
import _clients_table from './clients-table.bones.json'
import _manage_cases_table from './manage-cases-table.bones.json'
import _manage_lawyer_page from './manage-lawyer-page.bones.json'
import _settings from './settings.bones.json'
import _user_dashboard from './user-dashboard.bones.json'
import _view_cases_page from './view-cases-page.bones.json'

registerBones({
  "home": _home,
  "login": _login,
  "assign-lawyer": _assign_lawyer,
  "clients-table": _clients_table,
  "manage-cases-table": _manage_cases_table,
  "manage-lawyer-page": _manage_lawyer_page,
  "settings": _settings,
  "user-dashboard": _user_dashboard,
  "view-cases-page": _view_cases_page,
})
