"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _clients_table from './clients-table.bones.json'
import _profile_page from './profile-page.bones.json'
import _user_dashboard from './user-dashboard.bones.json'
import _view_cases_page from './view-cases-page.bones.json'
import _assign_lawyer from './assign-lawyer.bones.json'
import _documents_table from './documents-table.bones.json'
import _manage_cases_table from './manage-cases-table.bones.json'

registerBones({
  "clients-table": _clients_table,
  "profile-page": _profile_page,
  "user-dashboard": _user_dashboard,
  "view-cases-page": _view_cases_page,
  "assign-lawyer": _assign_lawyer,
  "documents-table": _documents_table,
  "manage-cases-table": _manage_cases_table,
})
